version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: tbl_einvoice_access
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - appnet

  go-app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app1
    restart: unless-stopped
    env_file:
      - ./apptest.env
    volumes:
      - ./logs:/app/logs
    networks:
      - appnet
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://go-app1:8091/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  go-app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app2
    restart: unless-stopped
    env_file:
      - ./apptest.env
    volumes:
      - ./logs:/app/logs
    networks:
      - appnet
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://go-app2:8091/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  go-app3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app3
    restart: unless-stopped
    env_file:
      - ./apptest.env
    volumes:
      - ./logs:/app/logs
    networks:
      - appnet
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://go-app3:8091/api/v1/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - go-app1
      - go-app2
      - go-app3
    networks:
      - appnet

volumes:
  pgdata:
  redisdata:
  grafana-storage:

networks:
  appnet:
    driver: bridge
